/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: s2_base_gcmessages.proto */

#ifndef PROTOBUF_C_s2_5fbase_5fgcmessages_2eproto__INCLUDED
#define PROTOBUF_C_s2_5fbase_5fgcmessages_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _CSOEconItemAttribute CSOEconItemAttribute;
typedef struct _CSOEconItemEquipped CSOEconItemEquipped;
typedef struct _CSOEconItem CSOEconItem;


/* --- enums --- */


/* --- messages --- */

struct  _CSOEconItemAttribute
{
  ProtobufCMessage base;
  protobuf_c_boolean has_def_index;
  uint32_t def_index;
  protobuf_c_boolean has_value;
  uint32_t value;
  protobuf_c_boolean has_value_bytes;
  ProtobufCBinaryData value_bytes;
};
#define CSOECON_ITEM_ATTRIBUTE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&csoecon_item_attribute__descriptor) \
    , 0,0, 0,0, 0,{0,NULL} }


struct  _CSOEconItemEquipped
{
  ProtobufCMessage base;
  protobuf_c_boolean has_new_class;
  uint32_t new_class;
  protobuf_c_boolean has_new_slot;
  uint32_t new_slot;
};
#define CSOECON_ITEM_EQUIPPED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&csoecon_item_equipped__descriptor) \
    , 0,0, 0,0 }


struct  _CSOEconItem
{
  ProtobufCMessage base;
  protobuf_c_boolean has_id;
  uint64_t id;
  protobuf_c_boolean has_account_id;
  uint32_t account_id;
  protobuf_c_boolean has_inventory;
  uint32_t inventory;
  protobuf_c_boolean has_def_index;
  uint32_t def_index;
  protobuf_c_boolean has_quantity;
  uint32_t quantity;
  protobuf_c_boolean has_level;
  uint32_t level;
  protobuf_c_boolean has_quality;
  uint32_t quality;
  protobuf_c_boolean has_flags;
  uint32_t flags;
  protobuf_c_boolean has_origin;
  uint32_t origin;
  size_t n_attribute;
  CSOEconItemAttribute **attribute;
  CSOEconItem *interior_item;
  protobuf_c_boolean has_in_use;
  protobuf_c_boolean in_use;
  protobuf_c_boolean has_style;
  uint32_t style;
  protobuf_c_boolean has_original_id;
  uint64_t original_id;
  size_t n_equipped_state;
  CSOEconItemEquipped **equipped_state;
};
#define CSOECON_ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&csoecon_item__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,1u, 0,1u, 0,4u, 0,0u, 0,0u, 0,NULL, NULL, 0,0, 0,0u, 0,0ull, 0,NULL }


/* CSOEconItemAttribute methods */
void   csoecon_item_attribute__init
                     (CSOEconItemAttribute         *message);
size_t csoecon_item_attribute__get_packed_size
                     (const CSOEconItemAttribute   *message);
size_t csoecon_item_attribute__pack
                     (const CSOEconItemAttribute   *message,
                      uint8_t             *out);
size_t csoecon_item_attribute__pack_to_buffer
                     (const CSOEconItemAttribute   *message,
                      ProtobufCBuffer     *buffer);
CSOEconItemAttribute *
       csoecon_item_attribute__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   csoecon_item_attribute__free_unpacked
                     (CSOEconItemAttribute *message,
                      ProtobufCAllocator *allocator);
/* CSOEconItemEquipped methods */
void   csoecon_item_equipped__init
                     (CSOEconItemEquipped         *message);
size_t csoecon_item_equipped__get_packed_size
                     (const CSOEconItemEquipped   *message);
size_t csoecon_item_equipped__pack
                     (const CSOEconItemEquipped   *message,
                      uint8_t             *out);
size_t csoecon_item_equipped__pack_to_buffer
                     (const CSOEconItemEquipped   *message,
                      ProtobufCBuffer     *buffer);
CSOEconItemEquipped *
       csoecon_item_equipped__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   csoecon_item_equipped__free_unpacked
                     (CSOEconItemEquipped *message,
                      ProtobufCAllocator *allocator);
/* CSOEconItem methods */
void   csoecon_item__init
                     (CSOEconItem         *message);
size_t csoecon_item__get_packed_size
                     (const CSOEconItem   *message);
size_t csoecon_item__pack
                     (const CSOEconItem   *message,
                      uint8_t             *out);
size_t csoecon_item__pack_to_buffer
                     (const CSOEconItem   *message,
                      ProtobufCBuffer     *buffer);
CSOEconItem *
       csoecon_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   csoecon_item__free_unpacked
                     (CSOEconItem *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CSOEconItemAttribute_Closure)
                 (const CSOEconItemAttribute *message,
                  void *closure_data);
typedef void (*CSOEconItemEquipped_Closure)
                 (const CSOEconItemEquipped *message,
                  void *closure_data);
typedef void (*CSOEconItem_Closure)
                 (const CSOEconItem *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor csoecon_item_attribute__descriptor;
extern const ProtobufCMessageDescriptor csoecon_item_equipped__descriptor;
extern const ProtobufCMessageDescriptor csoecon_item__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_s2_5fbase_5fgcmessages_2eproto__INCLUDED */
