/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: s2_dota_gcmessages_common.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include <libeffigywire/s2_dota_gcmessages_common.pb-c.h>
void   cmatch_player_ability_upgrade__init
                     (CMatchPlayerAbilityUpgrade         *message)
{
  static CMatchPlayerAbilityUpgrade init_value = CMATCH_PLAYER_ABILITY_UPGRADE__INIT;
  *message = init_value;
}
size_t cmatch_player_ability_upgrade__get_packed_size
                     (const CMatchPlayerAbilityUpgrade *message)
{
  assert(message->base.descriptor == &cmatch_player_ability_upgrade__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmatch_player_ability_upgrade__pack
                     (const CMatchPlayerAbilityUpgrade *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmatch_player_ability_upgrade__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmatch_player_ability_upgrade__pack_to_buffer
                     (const CMatchPlayerAbilityUpgrade *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmatch_player_ability_upgrade__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMatchPlayerAbilityUpgrade *
       cmatch_player_ability_upgrade__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMatchPlayerAbilityUpgrade *)
     protobuf_c_message_unpack (&cmatch_player_ability_upgrade__descriptor,
                                allocator, len, data);
}
void   cmatch_player_ability_upgrade__free_unpacked
                     (CMatchPlayerAbilityUpgrade *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cmatch_player_ability_upgrade__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmatch_additional_unit_inventory__init
                     (CMatchAdditionalUnitInventory         *message)
{
  static CMatchAdditionalUnitInventory init_value = CMATCH_ADDITIONAL_UNIT_INVENTORY__INIT;
  *message = init_value;
}
size_t cmatch_additional_unit_inventory__get_packed_size
                     (const CMatchAdditionalUnitInventory *message)
{
  assert(message->base.descriptor == &cmatch_additional_unit_inventory__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmatch_additional_unit_inventory__pack
                     (const CMatchAdditionalUnitInventory *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmatch_additional_unit_inventory__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmatch_additional_unit_inventory__pack_to_buffer
                     (const CMatchAdditionalUnitInventory *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmatch_additional_unit_inventory__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMatchAdditionalUnitInventory *
       cmatch_additional_unit_inventory__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMatchAdditionalUnitInventory *)
     protobuf_c_message_unpack (&cmatch_additional_unit_inventory__descriptor,
                                allocator, len, data);
}
void   cmatch_additional_unit_inventory__free_unpacked
                     (CMatchAdditionalUnitInventory *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cmatch_additional_unit_inventory__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmatch_hero_select_event__init
                     (CMatchHeroSelectEvent         *message)
{
  static CMatchHeroSelectEvent init_value = CMATCH_HERO_SELECT_EVENT__INIT;
  *message = init_value;
}
size_t cmatch_hero_select_event__get_packed_size
                     (const CMatchHeroSelectEvent *message)
{
  assert(message->base.descriptor == &cmatch_hero_select_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmatch_hero_select_event__pack
                     (const CMatchHeroSelectEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmatch_hero_select_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmatch_hero_select_event__pack_to_buffer
                     (const CMatchHeroSelectEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmatch_hero_select_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMatchHeroSelectEvent *
       cmatch_hero_select_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMatchHeroSelectEvent *)
     protobuf_c_message_unpack (&cmatch_hero_select_event__descriptor,
                                allocator, len, data);
}
void   cmatch_hero_select_event__free_unpacked
                     (CMatchHeroSelectEvent *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cmatch_hero_select_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmsg_dotamatch__player__custom_game_data__init
                     (CMsgDOTAMatch__Player__CustomGameData         *message)
{
  static CMsgDOTAMatch__Player__CustomGameData init_value = CMSG_DOTAMATCH__PLAYER__CUSTOM_GAME_DATA__INIT;
  *message = init_value;
}
void   cmsg_dotamatch__player__init
                     (CMsgDOTAMatch__Player         *message)
{
  static CMsgDOTAMatch__Player init_value = CMSG_DOTAMATCH__PLAYER__INIT;
  *message = init_value;
}
void   cmsg_dotamatch__broadcaster_info__init
                     (CMsgDOTAMatch__BroadcasterInfo         *message)
{
  static CMsgDOTAMatch__BroadcasterInfo init_value = CMSG_DOTAMATCH__BROADCASTER_INFO__INIT;
  *message = init_value;
}
void   cmsg_dotamatch__broadcaster_channel__init
                     (CMsgDOTAMatch__BroadcasterChannel         *message)
{
  static CMsgDOTAMatch__BroadcasterChannel init_value = CMSG_DOTAMATCH__BROADCASTER_CHANNEL__INIT;
  *message = init_value;
}
void   cmsg_dotamatch__custom_game_data__init
                     (CMsgDOTAMatch__CustomGameData         *message)
{
  static CMsgDOTAMatch__CustomGameData init_value = CMSG_DOTAMATCH__CUSTOM_GAME_DATA__INIT;
  *message = init_value;
}
void   cmsg_dotamatch__init
                     (CMsgDOTAMatch         *message)
{
  static CMsgDOTAMatch init_value = CMSG_DOTAMATCH__INIT;
  *message = init_value;
}
size_t cmsg_dotamatch__get_packed_size
                     (const CMsgDOTAMatch *message)
{
  assert(message->base.descriptor == &cmsg_dotamatch__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_dotamatch__pack
                     (const CMsgDOTAMatch *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmsg_dotamatch__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_dotamatch__pack_to_buffer
                     (const CMsgDOTAMatch *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmsg_dotamatch__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMsgDOTAMatch *
       cmsg_dotamatch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMsgDOTAMatch *)
     protobuf_c_message_unpack (&cmsg_dotamatch__descriptor,
                                allocator, len, data);
}
void   cmsg_dotamatch__free_unpacked
                     (CMsgDOTAMatch *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cmsg_dotamatch__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cmatch_player_ability_upgrade__field_descriptors[2] =
{
  {
    "ability",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMatchPlayerAbilityUpgrade, has_ability),
    offsetof(CMatchPlayerAbilityUpgrade, ability),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMatchPlayerAbilityUpgrade, has_time),
    offsetof(CMatchPlayerAbilityUpgrade, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmatch_player_ability_upgrade__field_indices_by_name[] = {
  0,   /* field[0] = ability */
  1,   /* field[1] = time */
};
static const ProtobufCIntRange cmatch_player_ability_upgrade__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cmatch_player_ability_upgrade__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMatchPlayerAbilityUpgrade",
  "CMatchPlayerAbilityUpgrade",
  "CMatchPlayerAbilityUpgrade",
  "",
  sizeof(CMatchPlayerAbilityUpgrade),
  2,
  cmatch_player_ability_upgrade__field_descriptors,
  cmatch_player_ability_upgrade__field_indices_by_name,
  1,  cmatch_player_ability_upgrade__number_ranges,
  (ProtobufCMessageInit) cmatch_player_ability_upgrade__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmatch_additional_unit_inventory__field_descriptors[2] =
{
  {
    "unit_name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMatchAdditionalUnitInventory, unit_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "items",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMatchAdditionalUnitInventory, n_items),
    offsetof(CMatchAdditionalUnitInventory, items),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmatch_additional_unit_inventory__field_indices_by_name[] = {
  1,   /* field[1] = items */
  0,   /* field[0] = unit_name */
};
static const ProtobufCIntRange cmatch_additional_unit_inventory__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cmatch_additional_unit_inventory__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMatchAdditionalUnitInventory",
  "CMatchAdditionalUnitInventory",
  "CMatchAdditionalUnitInventory",
  "",
  sizeof(CMatchAdditionalUnitInventory),
  2,
  cmatch_additional_unit_inventory__field_descriptors,
  cmatch_additional_unit_inventory__field_indices_by_name,
  1,  cmatch_additional_unit_inventory__number_ranges,
  (ProtobufCMessageInit) cmatch_additional_unit_inventory__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmatch_hero_select_event__field_descriptors[3] =
{
  {
    "is_pick",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMatchHeroSelectEvent, has_is_pick),
    offsetof(CMatchHeroSelectEvent, is_pick),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "team",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMatchHeroSelectEvent, has_team),
    offsetof(CMatchHeroSelectEvent, team),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hero_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMatchHeroSelectEvent, has_hero_id),
    offsetof(CMatchHeroSelectEvent, hero_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmatch_hero_select_event__field_indices_by_name[] = {
  2,   /* field[2] = hero_id */
  0,   /* field[0] = is_pick */
  1,   /* field[1] = team */
};
static const ProtobufCIntRange cmatch_hero_select_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cmatch_hero_select_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMatchHeroSelectEvent",
  "CMatchHeroSelectEvent",
  "CMatchHeroSelectEvent",
  "",
  sizeof(CMatchHeroSelectEvent),
  3,
  cmatch_hero_select_event__field_descriptors,
  cmatch_hero_select_event__field_indices_by_name,
  1,  cmatch_hero_select_event__number_ranges,
  (ProtobufCMessageInit) cmatch_hero_select_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_dotamatch__player__custom_game_data__field_descriptors[2] =
{
  {
    "dota_team",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player__CustomGameData, has_dota_team),
    offsetof(CMsgDOTAMatch__Player__CustomGameData, dota_team),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "winner",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgDOTAMatch__Player__CustomGameData, has_winner),
    offsetof(CMsgDOTAMatch__Player__CustomGameData, winner),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_dotamatch__player__custom_game_data__field_indices_by_name[] = {
  0,   /* field[0] = dota_team */
  1,   /* field[1] = winner */
};
static const ProtobufCIntRange cmsg_dotamatch__player__custom_game_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cmsg_dotamatch__player__custom_game_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgDOTAMatch.Player.CustomGameData",
  "CustomGameData",
  "CMsgDOTAMatch__Player__CustomGameData",
  "",
  sizeof(CMsgDOTAMatch__Player__CustomGameData),
  2,
  cmsg_dotamatch__player__custom_game_data__field_descriptors,
  cmsg_dotamatch__player__custom_game_data__field_indices_by_name,
  1,  cmsg_dotamatch__player__custom_game_data__number_ranges,
  (ProtobufCMessageInit) cmsg_dotamatch__player__custom_game_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_dotamatch__player__field_descriptors[50] =
{
  {
    "account_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_account_id),
    offsetof(CMsgDOTAMatch__Player, account_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player_slot",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_player_slot),
    offsetof(CMsgDOTAMatch__Player, player_slot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hero_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_hero_id),
    offsetof(CMsgDOTAMatch__Player, hero_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "item_0",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_item_0),
    offsetof(CMsgDOTAMatch__Player, item_0),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "item_1",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_item_1),
    offsetof(CMsgDOTAMatch__Player, item_1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "item_2",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_item_2),
    offsetof(CMsgDOTAMatch__Player, item_2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "item_3",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_item_3),
    offsetof(CMsgDOTAMatch__Player, item_3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "item_4",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_item_4),
    offsetof(CMsgDOTAMatch__Player, item_4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "item_5",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_item_5),
    offsetof(CMsgDOTAMatch__Player, item_5),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expected_team_contribution",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CMsgDOTAMatch__Player, has_expected_team_contribution),
    offsetof(CMsgDOTAMatch__Player, expected_team_contribution),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scaled_metric",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CMsgDOTAMatch__Player, has_scaled_metric),
    offsetof(CMsgDOTAMatch__Player, scaled_metric),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "previous_rank",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_previous_rank),
    offsetof(CMsgDOTAMatch__Player, previous_rank),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rank_change",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_rank_change),
    offsetof(CMsgDOTAMatch__Player, rank_change),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kills",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_kills),
    offsetof(CMsgDOTAMatch__Player, kills),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deaths",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_deaths),
    offsetof(CMsgDOTAMatch__Player, deaths),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "assists",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_assists),
    offsetof(CMsgDOTAMatch__Player, assists),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "leaver_status",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_leaver_status),
    offsetof(CMsgDOTAMatch__Player, leaver_status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gold",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_gold),
    offsetof(CMsgDOTAMatch__Player, gold),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_hits",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_last_hits),
    offsetof(CMsgDOTAMatch__Player, last_hits),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "denies",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_denies),
    offsetof(CMsgDOTAMatch__Player, denies),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gold_per_min",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_gold_per_min),
    offsetof(CMsgDOTAMatch__Player, gold_per_min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "XP_per_min",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_xp_per_min),
    offsetof(CMsgDOTAMatch__Player, xp_per_min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gold_spent",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_gold_spent),
    offsetof(CMsgDOTAMatch__Player, gold_spent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hero_damage",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_hero_damage),
    offsetof(CMsgDOTAMatch__Player, hero_damage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tower_damage",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_tower_damage),
    offsetof(CMsgDOTAMatch__Player, tower_damage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hero_healing",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_hero_healing),
    offsetof(CMsgDOTAMatch__Player, hero_healing),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "level",
    27,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_level),
    offsetof(CMsgDOTAMatch__Player, level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_last_seen",
    28,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_time_last_seen),
    offsetof(CMsgDOTAMatch__Player, time_last_seen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player_name",
    29,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgDOTAMatch__Player, player_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "support_ability_value",
    30,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_support_ability_value),
    offsetof(CMsgDOTAMatch__Player, support_ability_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "feeding_detected",
    32,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgDOTAMatch__Player, has_feeding_detected),
    offsetof(CMsgDOTAMatch__Player, feeding_detected),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "search_rank",
    34,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_search_rank),
    offsetof(CMsgDOTAMatch__Player, search_rank),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "search_rank_uncertainty",
    35,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_search_rank_uncertainty),
    offsetof(CMsgDOTAMatch__Player, search_rank_uncertainty),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rank_uncertainty_change",
    36,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CMsgDOTAMatch__Player, has_rank_uncertainty_change),
    offsetof(CMsgDOTAMatch__Player, rank_uncertainty_change),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hero_play_count",
    37,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_hero_play_count),
    offsetof(CMsgDOTAMatch__Player, hero_play_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "party_id",
    38,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(CMsgDOTAMatch__Player, has_party_id),
    offsetof(CMsgDOTAMatch__Player, party_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scaled_kills",
    39,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CMsgDOTAMatch__Player, has_scaled_kills),
    offsetof(CMsgDOTAMatch__Player, scaled_kills),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scaled_deaths",
    40,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CMsgDOTAMatch__Player, has_scaled_deaths),
    offsetof(CMsgDOTAMatch__Player, scaled_deaths),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scaled_assists",
    41,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CMsgDOTAMatch__Player, has_scaled_assists),
    offsetof(CMsgDOTAMatch__Player, scaled_assists),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "claimed_farm_gold",
    42,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_claimed_farm_gold),
    offsetof(CMsgDOTAMatch__Player, claimed_farm_gold),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "support_gold",
    43,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_support_gold),
    offsetof(CMsgDOTAMatch__Player, support_gold),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "claimed_denies",
    44,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_claimed_denies),
    offsetof(CMsgDOTAMatch__Player, claimed_denies),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "claimed_misses",
    45,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_claimed_misses),
    offsetof(CMsgDOTAMatch__Player, claimed_misses),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "misses",
    46,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_misses),
    offsetof(CMsgDOTAMatch__Player, misses),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ability_upgrades",
    47,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CMsgDOTAMatch__Player, n_ability_upgrades),
    offsetof(CMsgDOTAMatch__Player, ability_upgrades),
    &cmatch_player_ability_upgrade__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "additional_units_inventory",
    48,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CMsgDOTAMatch__Player, n_additional_units_inventory),
    offsetof(CMsgDOTAMatch__Player, additional_units_inventory),
    &cmatch_additional_unit_inventory__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "solo_rank",
    49,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgDOTAMatch__Player, has_solo_rank),
    offsetof(CMsgDOTAMatch__Player, solo_rank),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "custom_game_data",
    50,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CMsgDOTAMatch__Player, custom_game_data),
    &cmsg_dotamatch__player__custom_game_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "active_battle_pass",
    51,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgDOTAMatch__Player, has_active_battle_pass),
    offsetof(CMsgDOTAMatch__Player, active_battle_pass),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "net_worth",
    52,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__Player, has_net_worth),
    offsetof(CMsgDOTAMatch__Player, net_worth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_dotamatch__player__field_indices_by_name[] = {
  21,   /* field[21] = XP_per_min */
  44,   /* field[44] = ability_upgrades */
  0,   /* field[0] = account_id */
  48,   /* field[48] = active_battle_pass */
  45,   /* field[45] = additional_units_inventory */
  15,   /* field[15] = assists */
  41,   /* field[41] = claimed_denies */
  39,   /* field[39] = claimed_farm_gold */
  42,   /* field[42] = claimed_misses */
  47,   /* field[47] = custom_game_data */
  14,   /* field[14] = deaths */
  19,   /* field[19] = denies */
  9,   /* field[9] = expected_team_contribution */
  30,   /* field[30] = feeding_detected */
  17,   /* field[17] = gold */
  20,   /* field[20] = gold_per_min */
  22,   /* field[22] = gold_spent */
  23,   /* field[23] = hero_damage */
  25,   /* field[25] = hero_healing */
  2,   /* field[2] = hero_id */
  34,   /* field[34] = hero_play_count */
  3,   /* field[3] = item_0 */
  4,   /* field[4] = item_1 */
  5,   /* field[5] = item_2 */
  6,   /* field[6] = item_3 */
  7,   /* field[7] = item_4 */
  8,   /* field[8] = item_5 */
  13,   /* field[13] = kills */
  18,   /* field[18] = last_hits */
  16,   /* field[16] = leaver_status */
  26,   /* field[26] = level */
  43,   /* field[43] = misses */
  49,   /* field[49] = net_worth */
  35,   /* field[35] = party_id */
  28,   /* field[28] = player_name */
  1,   /* field[1] = player_slot */
  11,   /* field[11] = previous_rank */
  12,   /* field[12] = rank_change */
  33,   /* field[33] = rank_uncertainty_change */
  38,   /* field[38] = scaled_assists */
  37,   /* field[37] = scaled_deaths */
  36,   /* field[36] = scaled_kills */
  10,   /* field[10] = scaled_metric */
  31,   /* field[31] = search_rank */
  32,   /* field[32] = search_rank_uncertainty */
  46,   /* field[46] = solo_rank */
  29,   /* field[29] = support_ability_value */
  40,   /* field[40] = support_gold */
  27,   /* field[27] = time_last_seen */
  24,   /* field[24] = tower_damage */
};
static const ProtobufCIntRange cmsg_dotamatch__player__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 32, 30 },
  { 34, 31 },
  { 0, 50 }
};
const ProtobufCMessageDescriptor cmsg_dotamatch__player__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgDOTAMatch.Player",
  "Player",
  "CMsgDOTAMatch__Player",
  "",
  sizeof(CMsgDOTAMatch__Player),
  50,
  cmsg_dotamatch__player__field_descriptors,
  cmsg_dotamatch__player__field_indices_by_name,
  3,  cmsg_dotamatch__player__number_ranges,
  (ProtobufCMessageInit) cmsg_dotamatch__player__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_dotamatch__broadcaster_info__field_descriptors[2] =
{
  {
    "account_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch__BroadcasterInfo, has_account_id),
    offsetof(CMsgDOTAMatch__BroadcasterInfo, account_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgDOTAMatch__BroadcasterInfo, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_dotamatch__broadcaster_info__field_indices_by_name[] = {
  0,   /* field[0] = account_id */
  1,   /* field[1] = name */
};
static const ProtobufCIntRange cmsg_dotamatch__broadcaster_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cmsg_dotamatch__broadcaster_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgDOTAMatch.BroadcasterInfo",
  "BroadcasterInfo",
  "CMsgDOTAMatch__BroadcasterInfo",
  "",
  sizeof(CMsgDOTAMatch__BroadcasterInfo),
  2,
  cmsg_dotamatch__broadcaster_info__field_descriptors,
  cmsg_dotamatch__broadcaster_info__field_indices_by_name,
  1,  cmsg_dotamatch__broadcaster_info__number_ranges,
  (ProtobufCMessageInit) cmsg_dotamatch__broadcaster_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_dotamatch__broadcaster_channel__field_descriptors[4] =
{
  {
    "country_code",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgDOTAMatch__BroadcasterChannel, country_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgDOTAMatch__BroadcasterChannel, description),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "broadcaster_infos",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CMsgDOTAMatch__BroadcasterChannel, n_broadcaster_infos),
    offsetof(CMsgDOTAMatch__BroadcasterChannel, broadcaster_infos),
    &cmsg_dotamatch__broadcaster_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "language_code",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgDOTAMatch__BroadcasterChannel, language_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_dotamatch__broadcaster_channel__field_indices_by_name[] = {
  2,   /* field[2] = broadcaster_infos */
  0,   /* field[0] = country_code */
  1,   /* field[1] = description */
  3,   /* field[3] = language_code */
};
static const ProtobufCIntRange cmsg_dotamatch__broadcaster_channel__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor cmsg_dotamatch__broadcaster_channel__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgDOTAMatch.BroadcasterChannel",
  "BroadcasterChannel",
  "CMsgDOTAMatch__BroadcasterChannel",
  "",
  sizeof(CMsgDOTAMatch__BroadcasterChannel),
  4,
  cmsg_dotamatch__broadcaster_channel__field_descriptors,
  cmsg_dotamatch__broadcaster_channel__field_indices_by_name,
  1,  cmsg_dotamatch__broadcaster_channel__number_ranges,
  (ProtobufCMessageInit) cmsg_dotamatch__broadcaster_channel__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_dotamatch__custom_game_data__field_descriptors[2] =
{
  {
    "custom_game_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CMsgDOTAMatch__CustomGameData, has_custom_game_id),
    offsetof(CMsgDOTAMatch__CustomGameData, custom_game_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map_name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgDOTAMatch__CustomGameData, map_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_dotamatch__custom_game_data__field_indices_by_name[] = {
  0,   /* field[0] = custom_game_id */
  1,   /* field[1] = map_name */
};
static const ProtobufCIntRange cmsg_dotamatch__custom_game_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cmsg_dotamatch__custom_game_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgDOTAMatch.CustomGameData",
  "CustomGameData",
  "CMsgDOTAMatch__CustomGameData",
  "",
  sizeof(CMsgDOTAMatch__CustomGameData),
  2,
  cmsg_dotamatch__custom_game_data__field_descriptors,
  cmsg_dotamatch__custom_game_data__field_indices_by_name,
  1,  cmsg_dotamatch__custom_game_data__number_ranges,
  (ProtobufCMessageInit) cmsg_dotamatch__custom_game_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue cmsg_dotamatch__replay_state__enum_values_by_number[3] =
{
  { "REPLAY_AVAILABLE", "CMSG_DOTAMATCH__REPLAY_STATE__REPLAY_AVAILABLE", 0 },
  { "REPLAY_NOT_RECORDED", "CMSG_DOTAMATCH__REPLAY_STATE__REPLAY_NOT_RECORDED", 1 },
  { "REPLAY_EXPIRED", "CMSG_DOTAMATCH__REPLAY_STATE__REPLAY_EXPIRED", 2 },
};
static const ProtobufCIntRange cmsg_dotamatch__replay_state__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex cmsg_dotamatch__replay_state__enum_values_by_name[3] =
{
  { "REPLAY_AVAILABLE", 0 },
  { "REPLAY_EXPIRED", 2 },
  { "REPLAY_NOT_RECORDED", 1 },
};
const ProtobufCEnumDescriptor cmsg_dotamatch__replay_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CMsgDOTAMatch.ReplayState",
  "ReplayState",
  "CMsgDOTAMatch__ReplayState",
  "",
  3,
  cmsg_dotamatch__replay_state__enum_values_by_number,
  3,
  cmsg_dotamatch__replay_state__enum_values_by_name,
  1,
  cmsg_dotamatch__replay_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const DOTAGameMode cmsg_dotamatch__game_mode__default_value = DOTA__GAME_MODE__DOTA_GAMEMODE_NONE;
static const CMsgDOTAMatch__ReplayState cmsg_dotamatch__replay_state__default_value = CMSG_DOTAMATCH__REPLAY_STATE__REPLAY_AVAILABLE;
static const ProtobufCFieldDescriptor cmsg_dotamatch__field_descriptors[44] =
{
  {
    "good_guys_win",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgDOTAMatch, has_good_guys_win),
    offsetof(CMsgDOTAMatch, good_guys_win),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "duration",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_duration),
    offsetof(CMsgDOTAMatch, duration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "startTime",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(CMsgDOTAMatch, has_starttime),
    offsetof(CMsgDOTAMatch, starttime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "players",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CMsgDOTAMatch, n_players),
    offsetof(CMsgDOTAMatch, players),
    &cmsg_dotamatch__player__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "match_id",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CMsgDOTAMatch, has_match_id),
    offsetof(CMsgDOTAMatch, match_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tower_status",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, n_tower_status),
    offsetof(CMsgDOTAMatch, tower_status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "barracks_status",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, n_barracks_status),
    offsetof(CMsgDOTAMatch, barracks_status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cluster",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_cluster),
    offsetof(CMsgDOTAMatch, cluster),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "first_blood_time",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_first_blood_time),
    offsetof(CMsgDOTAMatch, first_blood_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "replay_salt",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(CMsgDOTAMatch, has_replay_salt),
    offsetof(CMsgDOTAMatch, replay_salt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_ip",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(CMsgDOTAMatch, has_server_ip),
    offsetof(CMsgDOTAMatch, server_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_port",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_server_port),
    offsetof(CMsgDOTAMatch, server_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lobby_type",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_lobby_type),
    offsetof(CMsgDOTAMatch, lobby_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "human_players",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_human_players),
    offsetof(CMsgDOTAMatch, human_players),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "average_skill",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_average_skill),
    offsetof(CMsgDOTAMatch, average_skill),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "game_balance",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CMsgDOTAMatch, has_game_balance),
    offsetof(CMsgDOTAMatch, game_balance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radiant_team_id",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_radiant_team_id),
    offsetof(CMsgDOTAMatch, radiant_team_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dire_team_id",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_dire_team_id),
    offsetof(CMsgDOTAMatch, dire_team_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "leagueid",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_leagueid),
    offsetof(CMsgDOTAMatch, leagueid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radiant_team_name",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgDOTAMatch, radiant_team_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dire_team_name",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgDOTAMatch, dire_team_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radiant_team_logo",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CMsgDOTAMatch, has_radiant_team_logo),
    offsetof(CMsgDOTAMatch, radiant_team_logo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dire_team_logo",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CMsgDOTAMatch, has_dire_team_logo),
    offsetof(CMsgDOTAMatch, dire_team_logo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radiant_team_complete",
    27,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_radiant_team_complete),
    offsetof(CMsgDOTAMatch, radiant_team_complete),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dire_team_complete",
    28,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_dire_team_complete),
    offsetof(CMsgDOTAMatch, dire_team_complete),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "positive_votes",
    29,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_positive_votes),
    offsetof(CMsgDOTAMatch, positive_votes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "negative_votes",
    30,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_negative_votes),
    offsetof(CMsgDOTAMatch, negative_votes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "game_mode",
    31,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CMsgDOTAMatch, has_game_mode),
    offsetof(CMsgDOTAMatch, game_mode),
    &dota__game_mode__descriptor,
    &cmsg_dotamatch__game_mode__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "picks_bans",
    32,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CMsgDOTAMatch, n_picks_bans),
    offsetof(CMsgDOTAMatch, picks_bans),
    &cmatch_hero_select_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "match_seq_num",
    33,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CMsgDOTAMatch, has_match_seq_num),
    offsetof(CMsgDOTAMatch, match_seq_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "replay_state",
    34,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CMsgDOTAMatch, has_replay_state),
    offsetof(CMsgDOTAMatch, replay_state),
    &cmsg_dotamatch__replay_state__descriptor,
    &cmsg_dotamatch__replay_state__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radiant_guild_id",
    35,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_radiant_guild_id),
    offsetof(CMsgDOTAMatch, radiant_guild_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dire_guild_id",
    36,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_dire_guild_id),
    offsetof(CMsgDOTAMatch, dire_guild_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radiant_team_tag",
    37,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgDOTAMatch, radiant_team_tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dire_team_tag",
    38,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgDOTAMatch, dire_team_tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "series_id",
    39,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_series_id),
    offsetof(CMsgDOTAMatch, series_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "series_type",
    40,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_series_type),
    offsetof(CMsgDOTAMatch, series_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "broadcaster_channels",
    43,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CMsgDOTAMatch, n_broadcaster_channels),
    offsetof(CMsgDOTAMatch, broadcaster_channels),
    &cmsg_dotamatch__broadcaster_channel__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "engine",
    44,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_engine),
    offsetof(CMsgDOTAMatch, engine),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "custom_game_data",
    45,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CMsgDOTAMatch, custom_game_data),
    &cmsg_dotamatch__custom_game_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "match_flags",
    46,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_match_flags),
    offsetof(CMsgDOTAMatch, match_flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "private_metadata_key",
    47,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(CMsgDOTAMatch, has_private_metadata_key),
    offsetof(CMsgDOTAMatch, private_metadata_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radiant_team_score",
    48,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_radiant_team_score),
    offsetof(CMsgDOTAMatch, radiant_team_score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dire_team_score",
    49,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgDOTAMatch, has_dire_team_score),
    offsetof(CMsgDOTAMatch, dire_team_score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_dotamatch__field_indices_by_name[] = {
  14,   /* field[14] = average_skill */
  6,   /* field[6] = barracks_status */
  37,   /* field[37] = broadcaster_channels */
  7,   /* field[7] = cluster */
  39,   /* field[39] = custom_game_data */
  32,   /* field[32] = dire_guild_id */
  24,   /* field[24] = dire_team_complete */
  17,   /* field[17] = dire_team_id */
  22,   /* field[22] = dire_team_logo */
  20,   /* field[20] = dire_team_name */
  43,   /* field[43] = dire_team_score */
  34,   /* field[34] = dire_team_tag */
  1,   /* field[1] = duration */
  38,   /* field[38] = engine */
  8,   /* field[8] = first_blood_time */
  15,   /* field[15] = game_balance */
  27,   /* field[27] = game_mode */
  0,   /* field[0] = good_guys_win */
  13,   /* field[13] = human_players */
  18,   /* field[18] = leagueid */
  12,   /* field[12] = lobby_type */
  40,   /* field[40] = match_flags */
  4,   /* field[4] = match_id */
  29,   /* field[29] = match_seq_num */
  26,   /* field[26] = negative_votes */
  28,   /* field[28] = picks_bans */
  3,   /* field[3] = players */
  25,   /* field[25] = positive_votes */
  41,   /* field[41] = private_metadata_key */
  31,   /* field[31] = radiant_guild_id */
  23,   /* field[23] = radiant_team_complete */
  16,   /* field[16] = radiant_team_id */
  21,   /* field[21] = radiant_team_logo */
  19,   /* field[19] = radiant_team_name */
  42,   /* field[42] = radiant_team_score */
  33,   /* field[33] = radiant_team_tag */
  9,   /* field[9] = replay_salt */
  30,   /* field[30] = replay_state */
  35,   /* field[35] = series_id */
  36,   /* field[36] = series_type */
  10,   /* field[10] = server_ip */
  11,   /* field[11] = server_port */
  2,   /* field[2] = startTime */
  5,   /* field[5] = tower_status */
};
static const ProtobufCIntRange cmsg_dotamatch__number_ranges[4 + 1] =
{
  { 2, 0 },
  { 8, 5 },
  { 12, 8 },
  { 43, 37 },
  { 0, 44 }
};
const ProtobufCMessageDescriptor cmsg_dotamatch__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgDOTAMatch",
  "CMsgDOTAMatch",
  "CMsgDOTAMatch",
  "",
  sizeof(CMsgDOTAMatch),
  44,
  cmsg_dotamatch__field_descriptors,
  cmsg_dotamatch__field_indices_by_name,
  4,  cmsg_dotamatch__number_ranges,
  (ProtobufCMessageInit) cmsg_dotamatch__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue dota__game_mode__enum_values_by_number[23] =
{
  { "DOTA_GAMEMODE_NONE", "DOTA__GAME_MODE__DOTA_GAMEMODE_NONE", 0 },
  { "DOTA_GAMEMODE_AP", "DOTA__GAME_MODE__DOTA_GAMEMODE_AP", 1 },
  { "DOTA_GAMEMODE_CM", "DOTA__GAME_MODE__DOTA_GAMEMODE_CM", 2 },
  { "DOTA_GAMEMODE_RD", "DOTA__GAME_MODE__DOTA_GAMEMODE_RD", 3 },
  { "DOTA_GAMEMODE_SD", "DOTA__GAME_MODE__DOTA_GAMEMODE_SD", 4 },
  { "DOTA_GAMEMODE_AR", "DOTA__GAME_MODE__DOTA_GAMEMODE_AR", 5 },
  { "DOTA_GAMEMODE_INTRO", "DOTA__GAME_MODE__DOTA_GAMEMODE_INTRO", 6 },
  { "DOTA_GAMEMODE_HW", "DOTA__GAME_MODE__DOTA_GAMEMODE_HW", 7 },
  { "DOTA_GAMEMODE_REVERSE_CM", "DOTA__GAME_MODE__DOTA_GAMEMODE_REVERSE_CM", 8 },
  { "DOTA_GAMEMODE_XMAS", "DOTA__GAME_MODE__DOTA_GAMEMODE_XMAS", 9 },
  { "DOTA_GAMEMODE_TUTORIAL", "DOTA__GAME_MODE__DOTA_GAMEMODE_TUTORIAL", 10 },
  { "DOTA_GAMEMODE_MO", "DOTA__GAME_MODE__DOTA_GAMEMODE_MO", 11 },
  { "DOTA_GAMEMODE_LP", "DOTA__GAME_MODE__DOTA_GAMEMODE_LP", 12 },
  { "DOTA_GAMEMODE_POOL1", "DOTA__GAME_MODE__DOTA_GAMEMODE_POOL1", 13 },
  { "DOTA_GAMEMODE_FH", "DOTA__GAME_MODE__DOTA_GAMEMODE_FH", 14 },
  { "DOTA_GAMEMODE_CUSTOM", "DOTA__GAME_MODE__DOTA_GAMEMODE_CUSTOM", 15 },
  { "DOTA_GAMEMODE_CD", "DOTA__GAME_MODE__DOTA_GAMEMODE_CD", 16 },
  { "DOTA_GAMEMODE_BD", "DOTA__GAME_MODE__DOTA_GAMEMODE_BD", 17 },
  { "DOTA_GAMEMODE_ABILITY_DRAFT", "DOTA__GAME_MODE__DOTA_GAMEMODE_ABILITY_DRAFT", 18 },
  { "DOTA_GAMEMODE_EVENT", "DOTA__GAME_MODE__DOTA_GAMEMODE_EVENT", 19 },
  { "DOTA_GAMEMODE_ARDM", "DOTA__GAME_MODE__DOTA_GAMEMODE_ARDM", 20 },
  { "DOTA_GAMEMODE_1V1MID", "DOTA__GAME_MODE__DOTA_GAMEMODE_1V1MID", 21 },
  { "DOTA_GAMEMODE_ALL_DRAFT", "DOTA__GAME_MODE__DOTA_GAMEMODE_ALL_DRAFT", 22 },
};
static const ProtobufCIntRange dota__game_mode__value_ranges[] = {
{0, 0},{0, 23}
};
static const ProtobufCEnumValueIndex dota__game_mode__enum_values_by_name[23] =
{
  { "DOTA_GAMEMODE_1V1MID", 21 },
  { "DOTA_GAMEMODE_ABILITY_DRAFT", 18 },
  { "DOTA_GAMEMODE_ALL_DRAFT", 22 },
  { "DOTA_GAMEMODE_AP", 1 },
  { "DOTA_GAMEMODE_AR", 5 },
  { "DOTA_GAMEMODE_ARDM", 20 },
  { "DOTA_GAMEMODE_BD", 17 },
  { "DOTA_GAMEMODE_CD", 16 },
  { "DOTA_GAMEMODE_CM", 2 },
  { "DOTA_GAMEMODE_CUSTOM", 15 },
  { "DOTA_GAMEMODE_EVENT", 19 },
  { "DOTA_GAMEMODE_FH", 14 },
  { "DOTA_GAMEMODE_HW", 7 },
  { "DOTA_GAMEMODE_INTRO", 6 },
  { "DOTA_GAMEMODE_LP", 12 },
  { "DOTA_GAMEMODE_MO", 11 },
  { "DOTA_GAMEMODE_NONE", 0 },
  { "DOTA_GAMEMODE_POOL1", 13 },
  { "DOTA_GAMEMODE_RD", 3 },
  { "DOTA_GAMEMODE_REVERSE_CM", 8 },
  { "DOTA_GAMEMODE_SD", 4 },
  { "DOTA_GAMEMODE_TUTORIAL", 10 },
  { "DOTA_GAMEMODE_XMAS", 9 },
};
const ProtobufCEnumDescriptor dota__game_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DOTA_GameMode",
  "DOTA_GameMode",
  "DOTAGameMode",
  "",
  23,
  dota__game_mode__enum_values_by_number,
  23,
  dota__game_mode__enum_values_by_name,
  1,
  dota__game_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
