/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: s2_netmessages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include <libeffigywire/s2_netmessages.pb-c.h>
void   csvcmsg__create_string_table__init
                     (CSVCMsgCreateStringTable         *message)
{
  static CSVCMsgCreateStringTable init_value = CSVCMSG__CREATE_STRING_TABLE__INIT;
  *message = init_value;
}
size_t csvcmsg__create_string_table__get_packed_size
                     (const CSVCMsgCreateStringTable *message)
{
  assert(message->base.descriptor == &csvcmsg__create_string_table__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t csvcmsg__create_string_table__pack
                     (const CSVCMsgCreateStringTable *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &csvcmsg__create_string_table__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t csvcmsg__create_string_table__pack_to_buffer
                     (const CSVCMsgCreateStringTable *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &csvcmsg__create_string_table__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CSVCMsgCreateStringTable *
       csvcmsg__create_string_table__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CSVCMsgCreateStringTable *)
     protobuf_c_message_unpack (&csvcmsg__create_string_table__descriptor,
                                allocator, len, data);
}
void   csvcmsg__create_string_table__free_unpacked
                     (CSVCMsgCreateStringTable *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &csvcmsg__create_string_table__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   csvcmsg__voice_data__init
                     (CSVCMsgVoiceData         *message)
{
  static CSVCMsgVoiceData init_value = CSVCMSG__VOICE_DATA__INIT;
  *message = init_value;
}
size_t csvcmsg__voice_data__get_packed_size
                     (const CSVCMsgVoiceData *message)
{
  assert(message->base.descriptor == &csvcmsg__voice_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t csvcmsg__voice_data__pack
                     (const CSVCMsgVoiceData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &csvcmsg__voice_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t csvcmsg__voice_data__pack_to_buffer
                     (const CSVCMsgVoiceData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &csvcmsg__voice_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CSVCMsgVoiceData *
       csvcmsg__voice_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CSVCMsgVoiceData *)
     protobuf_c_message_unpack (&csvcmsg__voice_data__descriptor,
                                allocator, len, data);
}
void   csvcmsg__voice_data__free_unpacked
                     (CSVCMsgVoiceData *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &csvcmsg__voice_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   csvcmsg__clear_all_string_tables__init
                     (CSVCMsgClearAllStringTables         *message)
{
  static CSVCMsgClearAllStringTables init_value = CSVCMSG__CLEAR_ALL_STRING_TABLES__INIT;
  *message = init_value;
}
size_t csvcmsg__clear_all_string_tables__get_packed_size
                     (const CSVCMsgClearAllStringTables *message)
{
  assert(message->base.descriptor == &csvcmsg__clear_all_string_tables__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t csvcmsg__clear_all_string_tables__pack
                     (const CSVCMsgClearAllStringTables *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &csvcmsg__clear_all_string_tables__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t csvcmsg__clear_all_string_tables__pack_to_buffer
                     (const CSVCMsgClearAllStringTables *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &csvcmsg__clear_all_string_tables__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CSVCMsgClearAllStringTables *
       csvcmsg__clear_all_string_tables__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CSVCMsgClearAllStringTables *)
     protobuf_c_message_unpack (&csvcmsg__clear_all_string_tables__descriptor,
                                allocator, len, data);
}
void   csvcmsg__clear_all_string_tables__free_unpacked
                     (CSVCMsgClearAllStringTables *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &csvcmsg__clear_all_string_tables__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto_flattened_serializer_field_t__init
                     (ProtoFlattenedSerializerFieldT         *message)
{
  static ProtoFlattenedSerializerFieldT init_value = PROTO_FLATTENED_SERIALIZER_FIELD_T__INIT;
  *message = init_value;
}
size_t proto_flattened_serializer_field_t__get_packed_size
                     (const ProtoFlattenedSerializerFieldT *message)
{
  assert(message->base.descriptor == &proto_flattened_serializer_field_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto_flattened_serializer_field_t__pack
                     (const ProtoFlattenedSerializerFieldT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto_flattened_serializer_field_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto_flattened_serializer_field_t__pack_to_buffer
                     (const ProtoFlattenedSerializerFieldT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto_flattened_serializer_field_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoFlattenedSerializerFieldT *
       proto_flattened_serializer_field_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoFlattenedSerializerFieldT *)
     protobuf_c_message_unpack (&proto_flattened_serializer_field_t__descriptor,
                                allocator, len, data);
}
void   proto_flattened_serializer_field_t__free_unpacked
                     (ProtoFlattenedSerializerFieldT *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &proto_flattened_serializer_field_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto_flattened_serializer_t__init
                     (ProtoFlattenedSerializerT         *message)
{
  static ProtoFlattenedSerializerT init_value = PROTO_FLATTENED_SERIALIZER_T__INIT;
  *message = init_value;
}
size_t proto_flattened_serializer_t__get_packed_size
                     (const ProtoFlattenedSerializerT *message)
{
  assert(message->base.descriptor == &proto_flattened_serializer_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto_flattened_serializer_t__pack
                     (const ProtoFlattenedSerializerT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto_flattened_serializer_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto_flattened_serializer_t__pack_to_buffer
                     (const ProtoFlattenedSerializerT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto_flattened_serializer_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoFlattenedSerializerT *
       proto_flattened_serializer_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoFlattenedSerializerT *)
     protobuf_c_message_unpack (&proto_flattened_serializer_t__descriptor,
                                allocator, len, data);
}
void   proto_flattened_serializer_t__free_unpacked
                     (ProtoFlattenedSerializerT *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &proto_flattened_serializer_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   csvcmsg__flattened_serializer__init
                     (CSVCMsgFlattenedSerializer         *message)
{
  static CSVCMsgFlattenedSerializer init_value = CSVCMSG__FLATTENED_SERIALIZER__INIT;
  *message = init_value;
}
size_t csvcmsg__flattened_serializer__get_packed_size
                     (const CSVCMsgFlattenedSerializer *message)
{
  assert(message->base.descriptor == &csvcmsg__flattened_serializer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t csvcmsg__flattened_serializer__pack
                     (const CSVCMsgFlattenedSerializer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &csvcmsg__flattened_serializer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t csvcmsg__flattened_serializer__pack_to_buffer
                     (const CSVCMsgFlattenedSerializer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &csvcmsg__flattened_serializer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CSVCMsgFlattenedSerializer *
       csvcmsg__flattened_serializer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CSVCMsgFlattenedSerializer *)
     protobuf_c_message_unpack (&csvcmsg__flattened_serializer__descriptor,
                                allocator, len, data);
}
void   csvcmsg__flattened_serializer__free_unpacked
                     (CSVCMsgFlattenedSerializer *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &csvcmsg__flattened_serializer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmsg_ipcaddress__init
                     (CMsgIPCAddress         *message)
{
  static CMsgIPCAddress init_value = CMSG_IPCADDRESS__INIT;
  *message = init_value;
}
size_t cmsg_ipcaddress__get_packed_size
                     (const CMsgIPCAddress *message)
{
  assert(message->base.descriptor == &cmsg_ipcaddress__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_ipcaddress__pack
                     (const CMsgIPCAddress *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmsg_ipcaddress__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_ipcaddress__pack_to_buffer
                     (const CMsgIPCAddress *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmsg_ipcaddress__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMsgIPCAddress *
       cmsg_ipcaddress__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMsgIPCAddress *)
     protobuf_c_message_unpack (&cmsg_ipcaddress__descriptor,
                                allocator, len, data);
}
void   cmsg_ipcaddress__free_unpacked
                     (CMsgIPCAddress *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cmsg_ipcaddress__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmsg_server_peer__init
                     (CMsgServerPeer         *message)
{
  static CMsgServerPeer init_value = CMSG_SERVER_PEER__INIT;
  *message = init_value;
}
size_t cmsg_server_peer__get_packed_size
                     (const CMsgServerPeer *message)
{
  assert(message->base.descriptor == &cmsg_server_peer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_server_peer__pack
                     (const CMsgServerPeer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmsg_server_peer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_server_peer__pack_to_buffer
                     (const CMsgServerPeer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmsg_server_peer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMsgServerPeer *
       cmsg_server_peer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMsgServerPeer *)
     protobuf_c_message_unpack (&cmsg_server_peer__descriptor,
                                allocator, len, data);
}
void   cmsg_server_peer__free_unpacked
                     (CMsgServerPeer *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cmsg_server_peer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   csvcmsg__peer_list__init
                     (CSVCMsgPeerList         *message)
{
  static CSVCMsgPeerList init_value = CSVCMSG__PEER_LIST__INIT;
  *message = init_value;
}
size_t csvcmsg__peer_list__get_packed_size
                     (const CSVCMsgPeerList *message)
{
  assert(message->base.descriptor == &csvcmsg__peer_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t csvcmsg__peer_list__pack
                     (const CSVCMsgPeerList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &csvcmsg__peer_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t csvcmsg__peer_list__pack_to_buffer
                     (const CSVCMsgPeerList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &csvcmsg__peer_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CSVCMsgPeerList *
       csvcmsg__peer_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CSVCMsgPeerList *)
     protobuf_c_message_unpack (&csvcmsg__peer_list__descriptor,
                                allocator, len, data);
}
void   csvcmsg__peer_list__free_unpacked
                     (CSVCMsgPeerList *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &csvcmsg__peer_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   csvcmsg__hltvstatus__init
                     (CSVCMsgHLTVStatus         *message)
{
  static CSVCMsgHLTVStatus init_value = CSVCMSG__HLTVSTATUS__INIT;
  *message = init_value;
}
size_t csvcmsg__hltvstatus__get_packed_size
                     (const CSVCMsgHLTVStatus *message)
{
  assert(message->base.descriptor == &csvcmsg__hltvstatus__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t csvcmsg__hltvstatus__pack
                     (const CSVCMsgHLTVStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &csvcmsg__hltvstatus__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t csvcmsg__hltvstatus__pack_to_buffer
                     (const CSVCMsgHLTVStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &csvcmsg__hltvstatus__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CSVCMsgHLTVStatus *
       csvcmsg__hltvstatus__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CSVCMsgHLTVStatus *)
     protobuf_c_message_unpack (&csvcmsg__hltvstatus__descriptor,
                                allocator, len, data);
}
void   csvcmsg__hltvstatus__free_unpacked
                     (CSVCMsgHLTVStatus *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &csvcmsg__hltvstatus__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor csvcmsg__create_string_table__field_descriptors[9] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CSVCMsgCreateStringTable, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_entries",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CSVCMsgCreateStringTable, has_num_entries),
    offsetof(CSVCMsgCreateStringTable, num_entries),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_data_fixed_size",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CSVCMsgCreateStringTable, has_user_data_fixed_size),
    offsetof(CSVCMsgCreateStringTable, user_data_fixed_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_data_size",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CSVCMsgCreateStringTable, has_user_data_size),
    offsetof(CSVCMsgCreateStringTable, user_data_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_data_size_bits",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CSVCMsgCreateStringTable, has_user_data_size_bits),
    offsetof(CSVCMsgCreateStringTable, user_data_size_bits),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CSVCMsgCreateStringTable, has_flags),
    offsetof(CSVCMsgCreateStringTable, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_data",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CSVCMsgCreateStringTable, has_string_data),
    offsetof(CSVCMsgCreateStringTable, string_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uncompressed_size",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CSVCMsgCreateStringTable, has_uncompressed_size),
    offsetof(CSVCMsgCreateStringTable, uncompressed_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_compressed",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CSVCMsgCreateStringTable, has_data_compressed),
    offsetof(CSVCMsgCreateStringTable, data_compressed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned csvcmsg__create_string_table__field_indices_by_name[] = {
  8,   /* field[8] = data_compressed */
  5,   /* field[5] = flags */
  0,   /* field[0] = name */
  1,   /* field[1] = num_entries */
  6,   /* field[6] = string_data */
  7,   /* field[7] = uncompressed_size */
  2,   /* field[2] = user_data_fixed_size */
  3,   /* field[3] = user_data_size */
  4,   /* field[4] = user_data_size_bits */
};
static const ProtobufCIntRange csvcmsg__create_string_table__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor csvcmsg__create_string_table__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CSVCMsg_CreateStringTable",
  "CSVCMsgCreateStringTable",
  "CSVCMsgCreateStringTable",
  "",
  sizeof(CSVCMsgCreateStringTable),
  9,
  csvcmsg__create_string_table__field_descriptors,
  csvcmsg__create_string_table__field_indices_by_name,
  1,  csvcmsg__create_string_table__number_ranges,
  (ProtobufCMessageInit) csvcmsg__create_string_table__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor csvcmsg__voice_data__field_descriptors[6] =
{
  {
    "audio",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CSVCMsgVoiceData, audio),
    &cmsg_voice_audio__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CSVCMsgVoiceData, has_client),
    offsetof(CSVCMsgVoiceData, client),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proximity",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CSVCMsgVoiceData, has_proximity),
    offsetof(CSVCMsgVoiceData, proximity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xuid",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(CSVCMsgVoiceData, has_xuid),
    offsetof(CSVCMsgVoiceData, xuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audible_mask",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CSVCMsgVoiceData, has_audible_mask),
    offsetof(CSVCMsgVoiceData, audible_mask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tick",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CSVCMsgVoiceData, has_tick),
    offsetof(CSVCMsgVoiceData, tick),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned csvcmsg__voice_data__field_indices_by_name[] = {
  4,   /* field[4] = audible_mask */
  0,   /* field[0] = audio */
  1,   /* field[1] = client */
  2,   /* field[2] = proximity */
  5,   /* field[5] = tick */
  3,   /* field[3] = xuid */
};
static const ProtobufCIntRange csvcmsg__voice_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor csvcmsg__voice_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CSVCMsg_VoiceData",
  "CSVCMsgVoiceData",
  "CSVCMsgVoiceData",
  "",
  sizeof(CSVCMsgVoiceData),
  6,
  csvcmsg__voice_data__field_descriptors,
  csvcmsg__voice_data__field_indices_by_name,
  1,  csvcmsg__voice_data__number_ranges,
  (ProtobufCMessageInit) csvcmsg__voice_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor csvcmsg__clear_all_string_tables__field_descriptors[2] =
{
  {
    "mapname",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CSVCMsgClearAllStringTables, mapname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map_crc",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CSVCMsgClearAllStringTables, has_map_crc),
    offsetof(CSVCMsgClearAllStringTables, map_crc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned csvcmsg__clear_all_string_tables__field_indices_by_name[] = {
  1,   /* field[1] = map_crc */
  0,   /* field[0] = mapname */
};
static const ProtobufCIntRange csvcmsg__clear_all_string_tables__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor csvcmsg__clear_all_string_tables__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CSVCMsg_ClearAllStringTables",
  "CSVCMsgClearAllStringTables",
  "CSVCMsgClearAllStringTables",
  "",
  sizeof(CSVCMsgClearAllStringTables),
  2,
  csvcmsg__clear_all_string_tables__field_descriptors,
  csvcmsg__clear_all_string_tables__field_indices_by_name,
  1,  csvcmsg__clear_all_string_tables__number_ranges,
  (ProtobufCMessageInit) csvcmsg__clear_all_string_tables__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto_flattened_serializer_field_t__field_descriptors[10] =
{
  {
    "var_type_sym",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ProtoFlattenedSerializerFieldT, has_var_type_sym),
    offsetof(ProtoFlattenedSerializerFieldT, var_type_sym),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "var_name_sym",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ProtoFlattenedSerializerFieldT, has_var_name_sym),
    offsetof(ProtoFlattenedSerializerFieldT, var_name_sym),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bit_count",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ProtoFlattenedSerializerFieldT, has_bit_count),
    offsetof(ProtoFlattenedSerializerFieldT, bit_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "low_value",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ProtoFlattenedSerializerFieldT, has_low_value),
    offsetof(ProtoFlattenedSerializerFieldT, low_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "high_value",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ProtoFlattenedSerializerFieldT, has_high_value),
    offsetof(ProtoFlattenedSerializerFieldT, high_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encode_flags",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ProtoFlattenedSerializerFieldT, has_encode_flags),
    offsetof(ProtoFlattenedSerializerFieldT, encode_flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field_serializer_name_sym",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ProtoFlattenedSerializerFieldT, has_field_serializer_name_sym),
    offsetof(ProtoFlattenedSerializerFieldT, field_serializer_name_sym),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field_serializer_version",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ProtoFlattenedSerializerFieldT, has_field_serializer_version),
    offsetof(ProtoFlattenedSerializerFieldT, field_serializer_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "send_node_sym",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ProtoFlattenedSerializerFieldT, has_send_node_sym),
    offsetof(ProtoFlattenedSerializerFieldT, send_node_sym),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "var_encoder_sym",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ProtoFlattenedSerializerFieldT, has_var_encoder_sym),
    offsetof(ProtoFlattenedSerializerFieldT, var_encoder_sym),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto_flattened_serializer_field_t__field_indices_by_name[] = {
  2,   /* field[2] = bit_count */
  5,   /* field[5] = encode_flags */
  6,   /* field[6] = field_serializer_name_sym */
  7,   /* field[7] = field_serializer_version */
  4,   /* field[4] = high_value */
  3,   /* field[3] = low_value */
  8,   /* field[8] = send_node_sym */
  9,   /* field[9] = var_encoder_sym */
  1,   /* field[1] = var_name_sym */
  0,   /* field[0] = var_type_sym */
};
static const ProtobufCIntRange proto_flattened_serializer_field_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor proto_flattened_serializer_field_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProtoFlattenedSerializerField_t",
  "ProtoFlattenedSerializerFieldT",
  "ProtoFlattenedSerializerFieldT",
  "",
  sizeof(ProtoFlattenedSerializerFieldT),
  10,
  proto_flattened_serializer_field_t__field_descriptors,
  proto_flattened_serializer_field_t__field_indices_by_name,
  1,  proto_flattened_serializer_field_t__number_ranges,
  (ProtobufCMessageInit) proto_flattened_serializer_field_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto_flattened_serializer_t__field_descriptors[3] =
{
  {
    "serializer_name_sym",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ProtoFlattenedSerializerT, has_serializer_name_sym),
    offsetof(ProtoFlattenedSerializerT, serializer_name_sym),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serializer_version",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ProtoFlattenedSerializerT, has_serializer_version),
    offsetof(ProtoFlattenedSerializerT, serializer_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fields_index",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ProtoFlattenedSerializerT, n_fields_index),
    offsetof(ProtoFlattenedSerializerT, fields_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto_flattened_serializer_t__field_indices_by_name[] = {
  2,   /* field[2] = fields_index */
  0,   /* field[0] = serializer_name_sym */
  1,   /* field[1] = serializer_version */
};
static const ProtobufCIntRange proto_flattened_serializer_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto_flattened_serializer_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProtoFlattenedSerializer_t",
  "ProtoFlattenedSerializerT",
  "ProtoFlattenedSerializerT",
  "",
  sizeof(ProtoFlattenedSerializerT),
  3,
  proto_flattened_serializer_t__field_descriptors,
  proto_flattened_serializer_t__field_indices_by_name,
  1,  proto_flattened_serializer_t__number_ranges,
  (ProtobufCMessageInit) proto_flattened_serializer_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor csvcmsg__flattened_serializer__field_descriptors[3] =
{
  {
    "serializers",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CSVCMsgFlattenedSerializer, n_serializers),
    offsetof(CSVCMsgFlattenedSerializer, serializers),
    &proto_flattened_serializer_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symbols",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(CSVCMsgFlattenedSerializer, n_symbols),
    offsetof(CSVCMsgFlattenedSerializer, symbols),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fields",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CSVCMsgFlattenedSerializer, n_fields),
    offsetof(CSVCMsgFlattenedSerializer, fields),
    &proto_flattened_serializer_field_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned csvcmsg__flattened_serializer__field_indices_by_name[] = {
  2,   /* field[2] = fields */
  0,   /* field[0] = serializers */
  1,   /* field[1] = symbols */
};
static const ProtobufCIntRange csvcmsg__flattened_serializer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor csvcmsg__flattened_serializer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CSVCMsg_FlattenedSerializer",
  "CSVCMsgFlattenedSerializer",
  "CSVCMsgFlattenedSerializer",
  "",
  sizeof(CSVCMsgFlattenedSerializer),
  3,
  csvcmsg__flattened_serializer__field_descriptors,
  csvcmsg__flattened_serializer__field_indices_by_name,
  1,  csvcmsg__flattened_serializer__number_ranges,
  (ProtobufCMessageInit) csvcmsg__flattened_serializer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_ipcaddress__field_descriptors[2] =
{
  {
    "computer_guid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(CMsgIPCAddress, has_computer_guid),
    offsetof(CMsgIPCAddress, computer_guid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "process_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgIPCAddress, has_process_id),
    offsetof(CMsgIPCAddress, process_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_ipcaddress__field_indices_by_name[] = {
  0,   /* field[0] = computer_guid */
  1,   /* field[1] = process_id */
};
static const ProtobufCIntRange cmsg_ipcaddress__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cmsg_ipcaddress__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgIPCAddress",
  "CMsgIPCAddress",
  "CMsgIPCAddress",
  "",
  sizeof(CMsgIPCAddress),
  2,
  cmsg_ipcaddress__field_descriptors,
  cmsg_ipcaddress__field_indices_by_name,
  1,  cmsg_ipcaddress__number_ranges,
  (ProtobufCMessageInit) cmsg_ipcaddress__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_server_peer__field_descriptors[6] =
{
  {
    "player_slot",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CMsgServerPeer, has_player_slot),
    offsetof(CMsgServerPeer, player_slot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "steamid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(CMsgServerPeer, has_steamid),
    offsetof(CMsgServerPeer, steamid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipc",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CMsgServerPeer, ipc),
    &cmsg_ipcaddress__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "they_hear_you",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgServerPeer, has_they_hear_you),
    offsetof(CMsgServerPeer, they_hear_you),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "you_hear_them",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgServerPeer, has_you_hear_them),
    offsetof(CMsgServerPeer, you_hear_them),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_listenserver_host",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgServerPeer, has_is_listenserver_host),
    offsetof(CMsgServerPeer, is_listenserver_host),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_server_peer__field_indices_by_name[] = {
  2,   /* field[2] = ipc */
  5,   /* field[5] = is_listenserver_host */
  0,   /* field[0] = player_slot */
  1,   /* field[1] = steamid */
  3,   /* field[3] = they_hear_you */
  4,   /* field[4] = you_hear_them */
};
static const ProtobufCIntRange cmsg_server_peer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor cmsg_server_peer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgServerPeer",
  "CMsgServerPeer",
  "CMsgServerPeer",
  "",
  sizeof(CMsgServerPeer),
  6,
  cmsg_server_peer__field_descriptors,
  cmsg_server_peer__field_indices_by_name,
  1,  cmsg_server_peer__number_ranges,
  (ProtobufCMessageInit) cmsg_server_peer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor csvcmsg__peer_list__field_descriptors[1] =
{
  {
    "peer",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CSVCMsgPeerList, n_peer),
    offsetof(CSVCMsgPeerList, peer),
    &cmsg_server_peer__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned csvcmsg__peer_list__field_indices_by_name[] = {
  0,   /* field[0] = peer */
};
static const ProtobufCIntRange csvcmsg__peer_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor csvcmsg__peer_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CSVCMsg_PeerList",
  "CSVCMsgPeerList",
  "CSVCMsgPeerList",
  "",
  sizeof(CSVCMsgPeerList),
  1,
  csvcmsg__peer_list__field_descriptors,
  csvcmsg__peer_list__field_indices_by_name,
  1,  csvcmsg__peer_list__number_ranges,
  (ProtobufCMessageInit) csvcmsg__peer_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor csvcmsg__hltvstatus__field_descriptors[4] =
{
  {
    "master",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CSVCMsgHLTVStatus, master),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clients",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CSVCMsgHLTVStatus, has_clients),
    offsetof(CSVCMsgHLTVStatus, clients),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slots",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CSVCMsgHLTVStatus, has_slots),
    offsetof(CSVCMsgHLTVStatus, slots),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proxies",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CSVCMsgHLTVStatus, has_proxies),
    offsetof(CSVCMsgHLTVStatus, proxies),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned csvcmsg__hltvstatus__field_indices_by_name[] = {
  1,   /* field[1] = clients */
  0,   /* field[0] = master */
  3,   /* field[3] = proxies */
  2,   /* field[2] = slots */
};
static const ProtobufCIntRange csvcmsg__hltvstatus__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor csvcmsg__hltvstatus__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CSVCMsg_HLTVStatus",
  "CSVCMsgHLTVStatus",
  "CSVCMsgHLTVStatus",
  "",
  sizeof(CSVCMsgHLTVStatus),
  4,
  csvcmsg__hltvstatus__field_descriptors,
  csvcmsg__hltvstatus__field_indices_by_name,
  1,  csvcmsg__hltvstatus__number_ranges,
  (ProtobufCMessageInit) csvcmsg__hltvstatus__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue clc__messages__enum_values_by_number[15] =
{
  { "clc_ClientInfo", "CLC__MESSAGES__clc_ClientInfo", 20 },
  { "clc_Move", "CLC__MESSAGES__clc_Move", 21 },
  { "clc_VoiceData", "CLC__MESSAGES__clc_VoiceData", 22 },
  { "clc_BaselineAck", "CLC__MESSAGES__clc_BaselineAck", 23 },
  { "clc_ListenEvents", "CLC__MESSAGES__clc_ListenEvents", 24 },
  { "clc_RespondCvarValue", "CLC__MESSAGES__clc_RespondCvarValue", 25 },
  { "clc_FileCRCCheck", "CLC__MESSAGES__clc_FileCRCCheck", 26 },
  { "clc_LoadingProgress", "CLC__MESSAGES__clc_LoadingProgress", 27 },
  { "clc_SplitPlayerConnect", "CLC__MESSAGES__clc_SplitPlayerConnect", 28 },
  { "clc_ClientMessage", "CLC__MESSAGES__clc_ClientMessage", 29 },
  { "clc_SplitPlayerDisconnect", "CLC__MESSAGES__clc_SplitPlayerDisconnect", 30 },
  { "clc_ServerStatus", "CLC__MESSAGES__clc_ServerStatus", 31 },
  { "clc_ServerPing", "CLC__MESSAGES__clc_ServerPing", 32 },
  { "clc_RequestPause", "CLC__MESSAGES__clc_RequestPause", 33 },
  { "clc_CmdKeyValues", "CLC__MESSAGES__clc_CmdKeyValues", 34 },
};
static const ProtobufCIntRange clc__messages__value_ranges[] = {
{20, 0},{0, 15}
};
static const ProtobufCEnumValueIndex clc__messages__enum_values_by_name[15] =
{
  { "clc_BaselineAck", 3 },
  { "clc_ClientInfo", 0 },
  { "clc_ClientMessage", 9 },
  { "clc_CmdKeyValues", 14 },
  { "clc_FileCRCCheck", 6 },
  { "clc_ListenEvents", 4 },
  { "clc_LoadingProgress", 7 },
  { "clc_Move", 1 },
  { "clc_RequestPause", 13 },
  { "clc_RespondCvarValue", 5 },
  { "clc_ServerPing", 12 },
  { "clc_ServerStatus", 11 },
  { "clc_SplitPlayerConnect", 8 },
  { "clc_SplitPlayerDisconnect", 10 },
  { "clc_VoiceData", 2 },
};
const ProtobufCEnumDescriptor clc__messages__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CLC_Messages",
  "CLC_Messages",
  "CLCMessages",
  "",
  15,
  clc__messages__enum_values_by_number,
  15,
  clc__messages__enum_values_by_name,
  1,
  clc__messages__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue svc__messages__enum_values_by_number[24] =
{
  { "svc_ServerInfo", "SVC__MESSAGES__svc_ServerInfo", 40 },
  { "svc_FlattenedSerializer", "SVC__MESSAGES__svc_FlattenedSerializer", 41 },
  { "svc_ClassInfo", "SVC__MESSAGES__svc_ClassInfo", 42 },
  { "svc_SetPause", "SVC__MESSAGES__svc_SetPause", 43 },
  { "svc_CreateStringTable", "SVC__MESSAGES__svc_CreateStringTable", 44 },
  { "svc_UpdateStringTable", "SVC__MESSAGES__svc_UpdateStringTable", 45 },
  { "svc_VoiceInit", "SVC__MESSAGES__svc_VoiceInit", 46 },
  { "svc_VoiceData", "SVC__MESSAGES__svc_VoiceData", 47 },
  { "svc_Print", "SVC__MESSAGES__svc_Print", 48 },
  { "svc_Sounds", "SVC__MESSAGES__svc_Sounds", 49 },
  { "svc_SetView", "SVC__MESSAGES__svc_SetView", 50 },
  { "svc_ClearAllStringTables", "SVC__MESSAGES__svc_ClearAllStringTables", 51 },
  { "svc_CmdKeyValues", "SVC__MESSAGES__svc_CmdKeyValues", 52 },
  { "svc_BSPDecal", "SVC__MESSAGES__svc_BSPDecal", 53 },
  { "svc_SplitScreen", "SVC__MESSAGES__svc_SplitScreen", 54 },
  { "svc_PacketEntities", "SVC__MESSAGES__svc_PacketEntities", 55 },
  { "svc_Prefetch", "SVC__MESSAGES__svc_Prefetch", 56 },
  { "svc_Menu", "SVC__MESSAGES__svc_Menu", 57 },
  { "svc_GetCvarValue", "SVC__MESSAGES__svc_GetCvarValue", 58 },
  { "svc_StopSound", "SVC__MESSAGES__svc_StopSound", 59 },
  { "svc_PeerList", "SVC__MESSAGES__svc_PeerList", 60 },
  { "svc_PacketReliable", "SVC__MESSAGES__svc_PacketReliable", 61 },
  { "svc_HLTVStatus", "SVC__MESSAGES__svc_HLTVStatus", 62 },
  { "svc_FullFrameSplit", "SVC__MESSAGES__svc_FullFrameSplit", 70 },
};
static const ProtobufCIntRange svc__messages__value_ranges[] = {
{40, 0},{70, 23},{0, 24}
};
static const ProtobufCEnumValueIndex svc__messages__enum_values_by_name[24] =
{
  { "svc_BSPDecal", 13 },
  { "svc_ClassInfo", 2 },
  { "svc_ClearAllStringTables", 11 },
  { "svc_CmdKeyValues", 12 },
  { "svc_CreateStringTable", 4 },
  { "svc_FlattenedSerializer", 1 },
  { "svc_FullFrameSplit", 23 },
  { "svc_GetCvarValue", 18 },
  { "svc_HLTVStatus", 22 },
  { "svc_Menu", 17 },
  { "svc_PacketEntities", 15 },
  { "svc_PacketReliable", 21 },
  { "svc_PeerList", 20 },
  { "svc_Prefetch", 16 },
  { "svc_Print", 8 },
  { "svc_ServerInfo", 0 },
  { "svc_SetPause", 3 },
  { "svc_SetView", 10 },
  { "svc_Sounds", 9 },
  { "svc_SplitScreen", 14 },
  { "svc_StopSound", 19 },
  { "svc_UpdateStringTable", 5 },
  { "svc_VoiceData", 7 },
  { "svc_VoiceInit", 6 },
};
const ProtobufCEnumDescriptor svc__messages__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SVC_Messages",
  "SVC_Messages",
  "SVCMessages",
  "",
  24,
  svc__messages__enum_values_by_number,
  24,
  svc__messages__enum_values_by_name,
  2,
  svc__messages__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
